### ISSUE TITLE
自动解析 URL 出现中文乱码

### ISSUE THREAD

**Issue by nickevin** [gefangshuai/wincndotnet#1]
URL: http://lavasoft.blog.51cto.com/62575/27069
![截图](http://i12.tietuku.com/a07ef3048ba85628.png)

**Comment by lifedever** [comment]
这个问题回头我看一下

**Comment by lifedever** [comment]
问题找到了，由于51cto整站使用的是gb2312的编码，而superagent默认是utf-8编码进行内容爬取，所以导致爬回的中文乱码了

我重新整理了一个版本，解决了这个问题，这里有一篇关于解决思路的详细说明：http://www.jianshu.com/p/abedebacd53c

**Comment by nickevin** [comment]
已更新，谢谢。
