### ISSUE TITLE
这是数据库没接还是？

### ISSUE THREAD

**Issue by xvinc** [gefangshuai/wincndotnet#3]
express-session deprecated undefined resave option; provide resave option app.js:47:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:47:9

/home/xvinc/wincndotnet/node_modules/mongoose/node_modules/mongodb/lib/server.js:242
        process.nextTick(function() { throw err; })
                                            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:983:19)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/root/.nvm/versions/v0.12.0/bin/node" "/root/.nvm/versions/v0.12.0/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! wincndotnet@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wincndotnet@0.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the wincndotnet package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls wincndotnet
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xvinc/wincndotnet/npm-debug.log

**Comment by lifedever** [comment]
npm install了吗？检查数据库是否可以正常访问
